# Generated by Django 5.1.6 on 2025-02-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0003_tbl_bloodbank_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_blooddonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blooddonate_unit', models.CharField(max_length=50)),
                ('blooddonate_date', models.CharField(max_length=50)),
                ('bloodbank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodbank')),
                ('bloodgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donor')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.CharField(max_length=50)),
                ('complaint_status', models.CharField(max_length=50)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('bloodgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_patient')),
            ],
        ),
    ]
