# Generated by Django 5.1.6 on 2025-03-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_rename_bloodbank_id_tbl_blooddonate_bloodbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blooddonate',
            name='blooddonate_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
