# Generated by Django 5.1.6 on 2025-03-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_alter_tbl_blooddonate_blooddonate_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
