# Generated by Django 5.1.6 on 2025-03-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_notification'),
        ('Donor', '0004_delete_tbl_complaint'),
        ('Guest', '0002_alter_tbl_donor_donor_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.CharField(max_length=50)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_patient')),
            ],
        ),
    ]
