# Generated by Django 5.1.6 on 2025-03-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
