# Generated by Django 5.1.6 on 2025-03-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0008_alter_tbl_complaint_donor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
