# Generated by Django 5.1.6 on 2025-03-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0006_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_date', models.DateField(auto_now_add=True)),
                ('camp_status', models.IntegerField(default=0)),
                ('camp_details', models.IntegerField(default=0)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodbank')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
