# Generated by Django 5.1.6 on 2025-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_camp',
            name='camp_details',
            field=models.CharField(max_length=50),
        ),
    ]
