# Generated by Django 5.1.6 on 2025-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbankapp', '0002_alter_tbl_camp_camp_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_camp',
            name='camp_date',
            field=models.DateField(),
        ),
    ]
