# Generated by Django 5.1.6 on 2025-02-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbank_name', models.CharField(max_length=50)),
                ('bloodbank_email', models.CharField(max_length=50)),
                ('bloodbank_contact', models.CharField(max_length=50)),
                ('bloodbank_address', models.CharField(max_length=50)),
                ('bloodbank_password', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_district')),
            ],
        ),
    ]
