# Generated by Django 5.1.6 on 2025-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_bloodbank_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complainttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complainttype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
