# Generated by Django 5.1.6 on 2025-02-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_tbl_complainttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complainttype',
            old_name='Complainttype_name',
            new_name='complainttype_name',
        ),
    ]
