# Generated by Django 5.1.6 on 2025-03-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_delete_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('notification_content', models.CharField(max_length=50)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodbank')),
            ],
        ),
    ]
