# Generated by Django 5.1.6 on 2025-03-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_tbl_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Notification',
        ),
    ]
