# Generated by Django 5.1.6 on 2025-02-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0003_tbl_bloodbank_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=50)),
                ('request_status', models.CharField(max_length=50)),
                ('request_quantitiy', models.CharField(max_length=50)),
                ('request_fordate', models.CharField(max_length=50)),
                ('bloodgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_patient')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
