# Generated by Django 5.1.6 on 2025-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_rename_bloodgroup_id_tbl_request_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
