# Generated by Django 5.1.6 on 2025-03-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_tbl_request_request_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
