# Generated by Django 5.1.6 on 2025-03-15 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0006_tbl_notification'),
        ('Guest', '0002_alter_tbl_donor_donor_photo_and_more'),
        ('Patient', '0005_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_quantitiy', models.CharField(max_length=50)),
                ('request_fordate', models.CharField(max_length=50)),
                ('request_location', models.CharField(max_length=50)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_patient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
