# Generated by Django 5.1.7 on 2025-04-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_donor_donor_photo_and_more'),
        ('Patient', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_donor'),
        ),
    ]
