# Generated by Django 5.1.6 on 2025-02-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0003_tbl_bloodbank_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_email', models.CharField(max_length=50)),
                ('donor_contact', models.CharField(max_length=50)),
                ('donor_address', models.CharField(max_length=50)),
                ('donor_status', models.CharField(max_length=50)),
                ('donor_photo', models.CharField(max_length=50)),
                ('donor_password', models.CharField(max_length=50)),
                ('disease_status', models.CharField(max_length=50)),
                ('donor_age', models.CharField(max_length=50)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=50)),
                ('patient_contact', models.CharField(max_length=50)),
                ('patient_address', models.CharField(max_length=50)),
                ('patient_photo', models.CharField(max_length=50)),
                ('patient_password', models.CharField(max_length=50)),
                ('patient_status', models.CharField(max_length=50)),
                ('patient_age', models.CharField(max_length=50)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_bloodgroup')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
