# Generated by Django 5.1.6 on 2025-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donor',
            name='donor_photo',
            field=models.FileField(upload_to='Assets/File/Donor/'),
        ),
        migrations.AlterField(
            model_name='tbl_donor',
            name='donor_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_photo',
            field=models.FileField(upload_to='Assets/File/Donor/'),
        ),
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_status',
            field=models.IntegerField(default=0),
        ),
    ]
